

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cqd"
version = "0.1.0"
description = "Computational Quantum Dynamics"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "matplotlib"
]

[tool.setuptools.packages.find]
where = ["src"]